### PR TITLE
Fix duplicate interface definition errors (RN v0.40+)

### PR DESCRIPTION
**Pull request by stami**
See breaking changes in React Native v0.40.0 

[https://github.com/facebook/react-native/releases/tag/v0.40.0](https://github.com/facebook/react-native/releases/tag/v0.40.0)

### CODE REVIEW

**Comment by stami** [comment]
@torifat If you have time to check. :)

**Comment by torifat** [comment]
@stami Sorry, I missed it somehow 😞 I will take a look soon.

**Comment by torifat** [comment]
@stami Thanks a log 👍

**Comment by stami** [comment]
Uhh, sorry to bug you but can you do a NPM update also? 😬

**Comment by torifat** [comment]
It's ok. Thanks for the reminder. I will release a new version tonight.

**Comment by torifat** [comment]
I have updated the Example and fixed a bug but I can't test it because I don't have a developer account ATM 😞 Can you please check if everything is working? Try to run the Example app.

I will release a new version with these changes.

**Pull request merged**
